### ISSUE TITLE
Can't build JAMI?

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/psimi#12]
When I try to build JAMI ("mvn -U clean package" from psi-jami directory) it fails. 
Failure occurs in the uniprot module.
Failed tests have following in common:

`Could not access HTTP invoker remote service at [http://www.ebi.ac.uk/uniprot/remotingAPI/remotingAPI/uniprotPagingService];`

Anyone know what this is about?

**Comment by tschaka1904** [comment]
Which part package of JAMI are you using? JAMI is still using the 'old' UniProt JAPI, which has been retired from last month on. We need to migrate it to the new one.

**Comment by colin-combe** [comment]
On 01/02/16 16:21, Maximilian Koch wrote:
> Which part package of JAMI are you using? 

I was checking if I could build it all by running maven from the 
psi-jami directory.

> JAMI is still using the 'old' UniProt JAPI, which has been retired 
> from last month on. We need to migrate it to the new one. 

I don't know how essential this uniprot module (uniprot bridges?) is in 
JAMI, we could comment out building that module if the other things will 
still work?

C

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
I have been updating all the pom.xml's in master. They were pointing to unitprot-kraken from 2015.02, which isn't available anymore. I have changed the version to RELEASE, which is pointing to the latest release of it. Anyway, we need to change this on some point to the new JAPI: http://www.ebi.ac.uk/uniprot/japi/index.html

But you should be able to use JAMI now. ;-) But you won't be able to receive any new proteins from now on.

**Comment by colin-combe** [comment]
Thanks Max - now I have the strange error shown below, it says UnknownHostException for "www.ebi.ac.uk" - any ideas whats wrong?
C


-------------------------------------------------------------------------------
Test set: psidev.psi.mi.jami.bridges.uniprot.UniprotGeneFetcherTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.096 sec <<< FAILURE!
test(psidev.psi.mi.jami.bridges.uniprot.UniprotGeneFetcherTest)  Time elapsed: 33.094 sec  <<< ERROR!
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://www.ebi.ac.uk/uniprot/remotingAPI/remotingAPI/uniprotPagingService]; nested exception is java.net.UnknownHostException: www.ebi.ac.uk: Name or service not known
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:216)

**Comment by colin-combe** [comment]
Ug, sorry about the formatting...

**Comment by tschaka1904** [comment]
Mhm.. that is odd. I can run the test without any problem. Can you please check that you don't have a the dependency: uk.ac.ebi.uniprot.kraken:uniprotjapi:2015.02 anymore. You must only have uk.ac.ebi.uniprot.kraken:uniprotjapi:2015.12

**Comment by colin-combe** [comment]
Thanks for your continued help with this Max; I've made a ticket for the using-new-JAPI issue mentioned above (issue #14).

Re. building JAMI - I am using "mvn -U clean install" which I thought would clear out old dependencies. (Incidentally, the two dependencies you mention above are the same - I guess you mean it should be uk.ac.ebi.uniprot.kraken:uniprotjapi:RELEASE .)

However, on a different computer today... and I have a different error (compilation error rather than test failure):-
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project jami-europubmedcentral: Compilation failure
[ERROR] /home/colin/test/psimi/psi-jami/jami-bridges/jami-europubmedcentral/src/main/java/psidev/psi/mi/jami/bridges/europubmedcentral/EuroPubmedCentralFetcher.java:[89,47] error: method searchPublications in interface WSCitationImpl cannot be applied to given types;
```

My java and mvn version info is:
```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /home/username/jdk1.7.0_75/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-4-686-pae", arch: "i386", family: "unix"
```
Any help much appreciated,
cheers,
c

**Comment by tschaka1904** [comment]
Hi Colin! I think, I had the same problem a few days ago, with one of the IntAct libs. You need to import this library: http://europepmc.org/JaxWs 

Hope this helps. Max

**Comment by colin-combe** [comment]
Thanks Max, 

> You need to import this library: http://europepmc.org/JaxWs

From the instructions I'm not quite sure how to install it... 
Would it be possible for the maven project to deal with this dependency? That would make it easier for people, otherwise we should say somewhere that this dependency needs to be installed manually.

best,
C

**Comment by tschaka1904** [comment]
This issue was moved to MICommunity/PSI-JAMI#4
