### ISSUE TITLE
Update to new Uniprot JAPI

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/psimi#14]
from @tschaka1904 
> I have been updating all the pom.xml's in master. They were pointing to unitprot-kraken from 2015.02, which isn't available anymore. I have changed the version to RELEASE, which is pointing to the latest release of it. Anyway, we need to change this on some point to the new JAPI: http://www.ebi.ac.uk/uniprot/japi/index.html

**Comment by tschaka1904** [comment]
This issue was moved to MICommunity/PSI-JAMI#3
