### ISSUE TITLE
Issue regd. VariableParameterValueComparator

### ISSUE THREAD

**Issue by git4anjali** [MICommunity/psimi#15]
@alexkalderimis @colin-combe @julie-sullivan @joshkh @tschaka1904 
Hi Everyone,
                      VariableParameterValueComparator in jami-core required a change since it was comparing only on the basis of value and order and not on description and thus was producing issues in Intact-Editor while trying to add two different VaraiableParameterValue having same Value.

This change has been done in the file VariableParameterValueComparator in 'jami-core' in the branch 'editor-44' . Also 1.2.3-SNAPSHOT of jami-core has been deployed in nexus for testing.

If anyone feels this change could pose a problem in their consumption of jami-core, please notify me and we probably can find a solution which fits requirements for all the conflicting projects.

If it this change seems to be in sync with other consumptions, I will go ahead and merge this in master and publish a new release version of jami-core in nexus.

Thanks&Regards,
Anjali

**Comment by tschaka1904** [comment]
This issue was moved to MICommunity/PSI-JAMI#2
