### ISSUE TITLE
Moving JAMI out of psimi

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psimi#16]
Hi all, 

we're doing here right now some little changes on JAMI (bug fixes, replacing old uniprot kraken etc.). This will also mean that we have to do a release on some point. If I do changes right now to JAMI, it would affect the whole psimi repo and I think this sounds not very clean. This is would like to move JAMI out of it. What do you think? 

Best regards,
Max

**Comment by colin-combe** [comment]
+1 to cleaning this up
It might be that JAMI is the only thing in here that's currently in use?


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
Do we want to keep in in MICommunity or do we want to put it into an own organisation? It will by about 15 repositories.

**Comment by tschaka1904** [comment]
Do we want to have on repo which is just PSI-JAMI and contains everything or do we want to have several repos like: jami-bridges, jami-enricher, jami-imex-updater etc. ? The second approach would look similar to: https://bitbucket.org/account/user/intact-ebi/projects/INTACTBRIDGES and follows the subtree pattern. But maybe its enough to have just a PSI-JAMI repo. What do you think ?

**Comment by colin-combe** [comment]
> Do we want to keep it in MICommunity or do we want to put it into an
> own organisation?
>

I don't mind. I've thought it might be an idea to tidy up by  moving the 
all the automated exports from googlecode/SF into a seperate 'archive' 
account and just have live projects in MICommunity.

Stating the obvious - don't lose the revision history :)
(also there's some tickets on the existing project).

it should be that the documentation from google-code is in a branch 
called 'wiki'

You could merge pull request #13 before forking / moving / doing 
whatever to it.


> It will by about 15 repositories.
>

Um, splitting JAMI into 15 repositories doesn't sound that great to me. 
IMO, its nice to have a top level directory from which you can build 
everything.


cheers,
c

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
This issue was moved to MICommunity/PSI-JAMI#1
