### ISSUE TITLE
Molecular sieving set as default detection methods

### ISSUE THREAD

**Issue by vtoure** [MICommunity/psimi#23]
Hi,
In the  [psimi/psimitab-parser/src/main/java/psidev/psi/mi/tab/mock/**PsimiTabMockBuilder.java**](https://github.com/MICommunity/psimi/blob/master/psimitab-parser/src/main/java/psidev/psi/mi/tab/mock/PsimiTabMockBuilder.java)
when creating a binary interaction `createInteraction( Interactor a, Interactor b )`, the detection method is by default set to "molecular sieving" (l.143).

`bi.getDetectionMethods().add( new CrossReferenceImpl("psi-mi", "MI:0071", "molecular sieving" ) );`

Any reason for this?
Thanks,
Vasundra

**Comment by bblodfon** [comment]
Hi Vasundra,

It seems to me that he just wants to create a mock mitab object and adds a detection method from the [available ones](https://www.ebi.ac.uk/ols/ontologies/MI/terms?obo_id=MI:0001), without any particular reason for that choice.

John

**Comment by vtoure** [comment]
Thanks John,
If no particular reason, then it would be better to either:

-  set it to a more generic method - the root (MI:0001) or 

- to the unspecified one (MI:0686) or 

- not set it at all (by default) to avoid creating distorted data?

Vasundra

**Comment by bblodfon** [comment]
This class was written was testing purposes (this particular example is used only in `escapeSpecialCharactersRoundtrip()` of the `PsimiTabWriterTest` class), so not much care was given for the data to "make sense" - there are a thousand other examples in this mocking class where the data inserted do not make "real" sense or are built from random strings...
